### ISSUE TITLE
Flake8 custom executable, complain from plone-api-flake8

### ISSUE THREAD

**Issue by nazrulworld** [nazrulworld/plone.recipe.sublimetext#2]
This is might be bug from https://pypi.python.org/pypi/flake8-plone-api
```
Traceback (most recent call last):
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/bin/flake8", line 31, in <module>
    sys.exit(flake8.main.cli.main())
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/home/nazrul/www/python/Doctor_Assistant/dra.didb/lib/python2.7/site-packages/flake8/checker.py", line 487, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/nazrul/APPS/buildout-cache/eggs/flake8_plone_api-1.2-py2.7.egg/flake8_plone_api.py", line 16, in run
    with open(self.filename) as f:
IOError: [Errno 2] No such file or directory: 'stdin' 
```

**Comment by nazrulworld** [comment]
Seems this issue is fixed and will be available at next version
https://github.com/gforcada/flake8-plone-api/pull/18
